name: digit_recognition

services:
  backend:
    image: backend
    build: 
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: frotend
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: iii_dude
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iii_dude -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: